#My properties file
#Wed Jun 24 15:07:26 IST 2026
Author=karthik
BASEURI=http\://64.227.160.186\:9000/v1/
Env=qa
Java\ Version=21.0.9
Operating\ System=Mac OS X
ProjectName=Phoenix test Automation Framework
